[project]
name = "dialogue-conductor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pysrt>=1.1.2",
    "tiktoken>=0.12.0",
]
